import type { DSAProblem, DSATopic } from "./store"

type ProblemSeed = { name: string; topic: DSATopic; difficulty: "easy" | "medium" | "hard"; url: string }

const SEED: ProblemSeed[] = [
  // Arrays & Hashing (9)
  { name: "Contains Duplicate", topic: "Arrays & Hashing", difficulty: "easy", url: "https://leetcode.com/problems/contains-duplicate/" },
  { name: "Valid Anagram", topic: "Arrays & Hashing", difficulty: "easy", url: "https://leetcode.com/problems/valid-anagram/" },
  { name: "Two Sum", topic: "Arrays & Hashing", difficulty: "easy", url: "https://leetcode.com/problems/two-sum/" },
  { name: "Group Anagrams", topic: "Arrays & Hashing", difficulty: "medium", url: "https://leetcode.com/problems/group-anagrams/" },
  { name: "Top K Frequent Elements", topic: "Arrays & Hashing", difficulty: "medium", url: "https://leetcode.com/problems/top-k-frequent-elements/" },
  { name: "Encode and Decode Strings", topic: "Arrays & Hashing", difficulty: "medium", url: "https://neetcode.io/problems/string-encode-and-decode" },
  { name: "Product of Array Except Self", topic: "Arrays & Hashing", difficulty: "medium", url: "https://leetcode.com/problems/product-of-array-except-self/" },
  { name: "Valid Sudoku", topic: "Arrays & Hashing", difficulty: "medium", url: "https://leetcode.com/problems/valid-sudoku/" },
  { name: "Longest Consecutive Sequence", topic: "Arrays & Hashing", difficulty: "medium", url: "https://leetcode.com/problems/longest-consecutive-sequence/" },
  // Two Pointers (5)
  { name: "Valid Palindrome", topic: "Two Pointers", difficulty: "easy", url: "https://leetcode.com/problems/valid-palindrome/" },
  { name: "Two Sum II - Input Array Is Sorted", topic: "Two Pointers", difficulty: "medium", url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
  { name: "3Sum", topic: "Two Pointers", difficulty: "medium", url: "https://leetcode.com/problems/3sum/" },
  { name: "Container With Most Water", topic: "Two Pointers", difficulty: "medium", url: "https://leetcode.com/problems/container-with-most-water/" },
  { name: "Trapping Rain Water", topic: "Two Pointers", difficulty: "hard", url: "https://leetcode.com/problems/trapping-rain-water/" },
  // Sliding Window (6)
  { name: "Best Time to Buy and Sell Stock", topic: "Sliding Window", difficulty: "easy", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
  { name: "Longest Substring Without Repeating Characters", topic: "Sliding Window", difficulty: "medium", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { name: "Longest Repeating Character Replacement", topic: "Sliding Window", difficulty: "medium", url: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
  { name: "Permutation in String", topic: "Sliding Window", difficulty: "medium", url: "https://leetcode.com/problems/permutation-in-string/" },
  { name: "Minimum Window Substring", topic: "Sliding Window", difficulty: "hard", url: "https://leetcode.com/problems/minimum-window-substring/" },
  { name: "Sliding Window Maximum", topic: "Sliding Window", difficulty: "hard", url: "https://leetcode.com/problems/sliding-window-maximum/" },
  // Stack (7)
  { name: "Valid Parentheses", topic: "Stack", difficulty: "easy", url: "https://leetcode.com/problems/valid-parentheses/" },
  { name: "Min Stack", topic: "Stack", difficulty: "medium", url: "https://leetcode.com/problems/min-stack/" },
  { name: "Evaluate Reverse Polish Notation", topic: "Stack", difficulty: "medium", url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
  { name: "Generate Parentheses", topic: "Stack", difficulty: "medium", url: "https://leetcode.com/problems/generate-parentheses/" },
  { name: "Daily Temperatures", topic: "Stack", difficulty: "medium", url: "https://leetcode.com/problems/daily-temperatures/" },
  { name: "Car Fleet", topic: "Stack", difficulty: "medium", url: "https://leetcode.com/problems/car-fleet/" },
  { name: "Largest Rectangle in Histogram", topic: "Stack", difficulty: "hard", url: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
  // Binary Search (7)
  { name: "Binary Search", topic: "Binary Search", difficulty: "easy", url: "https://leetcode.com/problems/binary-search/" },
  { name: "Search a 2D Matrix", topic: "Binary Search", difficulty: "medium", url: "https://leetcode.com/problems/search-a-2d-matrix/" },
  { name: "Koko Eating Bananas", topic: "Binary Search", difficulty: "medium", url: "https://leetcode.com/problems/koko-eating-bananas/" },
  { name: "Find Minimum in Rotated Sorted Array", topic: "Binary Search", difficulty: "medium", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
  { name: "Search in Rotated Sorted Array", topic: "Binary Search", difficulty: "medium", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { name: "Time Based Key-Value Store", topic: "Binary Search", difficulty: "medium", url: "https://leetcode.com/problems/time-based-key-value-store/" },
  { name: "Median of Two Sorted Arrays", topic: "Binary Search", difficulty: "hard", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  // Linked List (11)
  { name: "Reverse Linked List", topic: "Linked List", difficulty: "easy", url: "https://leetcode.com/problems/reverse-linked-list/" },
  { name: "Merge Two Sorted Lists", topic: "Linked List", difficulty: "easy", url: "https://leetcode.com/problems/merge-two-sorted-lists/" },
  { name: "Linked List Cycle", topic: "Linked List", difficulty: "easy", url: "https://leetcode.com/problems/linked-list-cycle/" },
  { name: "Reorder List", topic: "Linked List", difficulty: "medium", url: "https://leetcode.com/problems/reorder-list/" },
  { name: "Remove Nth Node From End of List", topic: "Linked List", difficulty: "medium", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
  { name: "Copy List with Random Pointer", topic: "Linked List", difficulty: "medium", url: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
  { name: "Add Two Numbers", topic: "Linked List", difficulty: "medium", url: "https://leetcode.com/problems/add-two-numbers/" },
  { name: "Find the Duplicate Number", topic: "Linked List", difficulty: "medium", url: "https://leetcode.com/problems/find-the-duplicate-number/" },
  { name: "LRU Cache", topic: "Linked List", difficulty: "medium", url: "https://leetcode.com/problems/lru-cache/" },
  { name: "Merge K Sorted Lists", topic: "Linked List", difficulty: "hard", url: "https://leetcode.com/problems/merge-k-sorted-lists/" },
  { name: "Reverse Nodes in k-Group", topic: "Linked List", difficulty: "hard", url: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  // Trees (15)
  { name: "Invert Binary Tree", topic: "Trees", difficulty: "easy", url: "https://leetcode.com/problems/invert-binary-tree/" },
  { name: "Maximum Depth of Binary Tree", topic: "Trees", difficulty: "easy", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
  { name: "Diameter of Binary Tree", topic: "Trees", difficulty: "easy", url: "https://leetcode.com/problems/diameter-of-binary-tree/" },
  { name: "Balanced Binary Tree", topic: "Trees", difficulty: "easy", url: "https://leetcode.com/problems/balanced-binary-tree/" },
  { name: "Same Tree", topic: "Trees", difficulty: "easy", url: "https://leetcode.com/problems/same-tree/" },
  { name: "Subtree of Another Tree", topic: "Trees", difficulty: "easy", url: "https://leetcode.com/problems/subtree-of-another-tree/" },
  { name: "Lowest Common Ancestor of a BST", topic: "Trees", difficulty: "medium", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
  { name: "Binary Tree Level Order Traversal", topic: "Trees", difficulty: "medium", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
  { name: "Binary Tree Right Side View", topic: "Trees", difficulty: "medium", url: "https://leetcode.com/problems/binary-tree-right-side-view/" },
  { name: "Count Good Nodes in Binary Tree", topic: "Trees", difficulty: "medium", url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/" },
  { name: "Validate Binary Search Tree", topic: "Trees", difficulty: "medium", url: "https://leetcode.com/problems/validate-binary-search-tree/" },
  { name: "Kth Smallest Element in a BST", topic: "Trees", difficulty: "medium", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
  { name: "Construct Binary Tree from Preorder and Inorder Traversal", topic: "Trees", difficulty: "medium", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
  { name: "Binary Tree Maximum Path Sum", topic: "Trees", difficulty: "hard", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
  { name: "Serialize and Deserialize Binary Tree", topic: "Trees", difficulty: "hard", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
  // Tries (3)
  { name: "Implement Trie (Prefix Tree)", topic: "Tries", difficulty: "medium", url: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
  { name: "Design Add and Search Words Data Structure", topic: "Tries", difficulty: "medium", url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
  { name: "Word Search II", topic: "Tries", difficulty: "hard", url: "https://leetcode.com/problems/word-search-ii/" },
  // Heap / Priority Queue (7)
  { name: "Kth Largest Element in a Stream", topic: "Heap", difficulty: "easy", url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
  { name: "Last Stone Weight", topic: "Heap", difficulty: "easy", url: "https://leetcode.com/problems/last-stone-weight/" },
  { name: "K Closest Points to Origin", topic: "Heap", difficulty: "medium", url: "https://leetcode.com/problems/k-closest-points-to-origin/" },
  { name: "Kth Largest Element in an Array", topic: "Heap", difficulty: "medium", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
  { name: "Task Scheduler", topic: "Heap", difficulty: "medium", url: "https://leetcode.com/problems/task-scheduler/" },
  { name: "Design Twitter", topic: "Heap", difficulty: "medium", url: "https://leetcode.com/problems/design-twitter/" },
  { name: "Find Median from Data Stream", topic: "Heap", difficulty: "hard", url: "https://leetcode.com/problems/find-median-from-data-stream/" },
  // Backtracking (9)
  { name: "Subsets", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/subsets/" },
  { name: "Combination Sum", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/combination-sum/" },
  { name: "Permutations", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/permutations/" },
  { name: "Subsets II", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/subsets-ii/" },
  { name: "Combination Sum II", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/combination-sum-ii/" },
  { name: "Word Search", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/word-search/" },
  { name: "Palindrome Partitioning", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/palindrome-partitioning/" },
  { name: "Letter Combinations of a Phone Number", topic: "Backtracking", difficulty: "medium", url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
  { name: "N-Queens", topic: "Backtracking", difficulty: "hard", url: "https://leetcode.com/problems/n-queens/" },
  // Graphs (13)
  { name: "Number of Islands", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/number-of-islands/" },
  { name: "Clone Graph", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/clone-graph/" },
  { name: "Max Area of Island", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/max-area-of-island/" },
  { name: "Pacific Atlantic Water Flow", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/pacific-atlantic-water-flow/" },
  { name: "Surrounded Regions", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/surrounded-regions/" },
  { name: "Rotting Oranges", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/rotting-oranges/" },
  { name: "Walls and Gates", topic: "Graphs", difficulty: "medium", url: "https://neetcode.io/problems/islands-and-treasure" },
  { name: "Course Schedule", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/course-schedule/" },
  { name: "Course Schedule II", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/course-schedule-ii/" },
  { name: "Redundant Connection", topic: "Graphs", difficulty: "medium", url: "https://leetcode.com/problems/redundant-connection/" },
  { name: "Number of Connected Components in an Undirected Graph", topic: "Graphs", difficulty: "medium", url: "https://neetcode.io/problems/count-connected-components" },
  { name: "Graph Valid Tree", topic: "Graphs", difficulty: "medium", url: "https://neetcode.io/problems/valid-tree" },
  { name: "Word Ladder", topic: "Graphs", difficulty: "hard", url: "https://leetcode.com/problems/word-ladder/" },
  // Advanced Graphs (6)
  { name: "Reconstruct Itinerary", topic: "Advanced Graphs", difficulty: "hard", url: "https://leetcode.com/problems/reconstruct-itinerary/" },
  { name: "Min Cost to Connect All Points", topic: "Advanced Graphs", difficulty: "medium", url: "https://leetcode.com/problems/min-cost-to-connect-all-points/" },
  { name: "Network Delay Time", topic: "Advanced Graphs", difficulty: "medium", url: "https://leetcode.com/problems/network-delay-time/" },
  { name: "Swim in Rising Water", topic: "Advanced Graphs", difficulty: "hard", url: "https://leetcode.com/problems/swim-in-rising-water/" },
  { name: "Alien Dictionary", topic: "Advanced Graphs", difficulty: "hard", url: "https://neetcode.io/problems/foreign-dictionary" },
  { name: "Cheapest Flights Within K Stops", topic: "Advanced Graphs", difficulty: "medium", url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
  // 1-D Dynamic Programming (12)
  { name: "Climbing Stairs", topic: "1-D DP", difficulty: "easy", url: "https://leetcode.com/problems/climbing-stairs/" },
  { name: "Min Cost Climbing Stairs", topic: "1-D DP", difficulty: "easy", url: "https://leetcode.com/problems/min-cost-climbing-stairs/" },
  { name: "House Robber", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/house-robber/" },
  { name: "House Robber II", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/house-robber-ii/" },
  { name: "Longest Palindromic Substring", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/longest-palindromic-substring/" },
  { name: "Palindromic Substrings", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/palindromic-substrings/" },
  { name: "Decode Ways", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/decode-ways/" },
  { name: "Coin Change", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/coin-change/" },
  { name: "Maximum Product Subarray", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/maximum-product-subarray/" },
  { name: "Word Break", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/word-break/" },
  { name: "Longest Increasing Subsequence", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/longest-increasing-subsequence/" },
  { name: "Partition Equal Subset Sum", topic: "1-D DP", difficulty: "medium", url: "https://leetcode.com/problems/partition-equal-subset-sum/" },
  // 2-D Dynamic Programming (11)
  { name: "Unique Paths", topic: "2-D DP", difficulty: "medium", url: "https://leetcode.com/problems/unique-paths/" },
  { name: "Longest Common Subsequence", topic: "2-D DP", difficulty: "medium", url: "https://leetcode.com/problems/longest-common-subsequence/" },
  { name: "Best Time to Buy and Sell Stock with Cooldown", topic: "2-D DP", difficulty: "medium", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/" },
  { name: "Coin Change II", topic: "2-D DP", difficulty: "medium", url: "https://leetcode.com/problems/coin-change-ii/" },
  { name: "Target Sum", topic: "2-D DP", difficulty: "medium", url: "https://leetcode.com/problems/target-sum/" },
  { name: "Interleaving String", topic: "2-D DP", difficulty: "medium", url: "https://leetcode.com/problems/interleaving-string/" },
  { name: "Longest Increasing Path in a Matrix", topic: "2-D DP", difficulty: "hard", url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/" },
  { name: "Distinct Subsequences", topic: "2-D DP", difficulty: "hard", url: "https://leetcode.com/problems/distinct-subsequences/" },
  { name: "Edit Distance", topic: "2-D DP", difficulty: "medium", url: "https://leetcode.com/problems/edit-distance/" },
  { name: "Burst Balloons", topic: "2-D DP", difficulty: "hard", url: "https://leetcode.com/problems/burst-balloons/" },
  { name: "Regular Expression Matching", topic: "2-D DP", difficulty: "hard", url: "https://leetcode.com/problems/regular-expression-matching/" },
  // Greedy (8)
  { name: "Maximum Subarray", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/maximum-subarray/" },
  { name: "Jump Game", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/jump-game/" },
  { name: "Jump Game II", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/jump-game-ii/" },
  { name: "Gas Station", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/gas-station/" },
  { name: "Hand of Straights", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/hand-of-straights/" },
  { name: "Merge Triplets to Form Target Triplet", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/" },
  { name: "Partition Labels", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/partition-labels/" },
  { name: "Valid Parenthesis String", topic: "Greedy", difficulty: "medium", url: "https://leetcode.com/problems/valid-parenthesis-string/" },
  // Intervals (6)
  { name: "Insert Interval", topic: "Intervals", difficulty: "medium", url: "https://leetcode.com/problems/insert-interval/" },
  { name: "Merge Intervals", topic: "Intervals", difficulty: "medium", url: "https://leetcode.com/problems/merge-intervals/" },
  { name: "Non-overlapping Intervals", topic: "Intervals", difficulty: "medium", url: "https://leetcode.com/problems/non-overlapping-intervals/" },
  { name: "Meeting Rooms", topic: "Intervals", difficulty: "easy", url: "https://neetcode.io/problems/meeting-schedule" },
  { name: "Meeting Rooms II", topic: "Intervals", difficulty: "medium", url: "https://neetcode.io/problems/meeting-schedule-ii" },
  { name: "Minimum Interval to Include Each Query", topic: "Intervals", difficulty: "hard", url: "https://leetcode.com/problems/minimum-interval-to-include-each-query/" },
  // Math & Geometry (8)
  { name: "Rotate Image", topic: "Math & Geometry", difficulty: "medium", url: "https://leetcode.com/problems/rotate-image/" },
  { name: "Spiral Matrix", topic: "Math & Geometry", difficulty: "medium", url: "https://leetcode.com/problems/spiral-matrix/" },
  { name: "Set Matrix Zeroes", topic: "Math & Geometry", difficulty: "medium", url: "https://leetcode.com/problems/set-matrix-zeroes/" },
  { name: "Happy Number", topic: "Math & Geometry", difficulty: "easy", url: "https://leetcode.com/problems/happy-number/" },
  { name: "Plus One", topic: "Math & Geometry", difficulty: "easy", url: "https://leetcode.com/problems/plus-one/" },
  { name: "Pow(x, n)", topic: "Math & Geometry", difficulty: "medium", url: "https://leetcode.com/problems/powx-n/" },
  { name: "Multiply Strings", topic: "Math & Geometry", difficulty: "medium", url: "https://leetcode.com/problems/multiply-strings/" },
  { name: "Detect Squares", topic: "Math & Geometry", difficulty: "medium", url: "https://leetcode.com/problems/detect-squares/" },
  // Bit Manipulation (7)
  { name: "Single Number", topic: "Bit Manipulation", difficulty: "easy", url: "https://leetcode.com/problems/single-number/" },
  { name: "Number of 1 Bits", topic: "Bit Manipulation", difficulty: "easy", url: "https://leetcode.com/problems/number-of-1-bits/" },
  { name: "Counting Bits", topic: "Bit Manipulation", difficulty: "easy", url: "https://leetcode.com/problems/counting-bits/" },
  { name: "Reverse Bits", topic: "Bit Manipulation", difficulty: "easy", url: "https://leetcode.com/problems/reverse-bits/" },
  { name: "Missing Number", topic: "Bit Manipulation", difficulty: "easy", url: "https://leetcode.com/problems/missing-number/" },
  { name: "Sum of Two Integers", topic: "Bit Manipulation", difficulty: "medium", url: "https://leetcode.com/problems/sum-of-two-integers/" },
  { name: "Reverse Integer", topic: "Bit Manipulation", difficulty: "medium", url: "https://leetcode.com/problems/reverse-integer/" },
]

export function buildNeetCode150(): DSAProblem[] {
  return SEED.map((s, i) => ({
    id: `neet-${i + 1}`,
    name: s.name,
    topic: s.topic,
    difficulty: s.difficulty,
    url: s.url,
    date_solved: null,
    time_taken: null,
    solved_independently: true,
    needed_hint: false,
    needed_solution: false,
    reattempt_date: null,
    confidence: 3,
    is_mastered: false,
    notes: "",
  }))
}

export const NEETCODE_COUNT = SEED.length // 150